// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRy7V1svpKFLeV4j2EGxe64BT4lAVbRl8',
    appId: '1:818592913245:web:c2a998149a9a4d06acfab4',
    messagingSenderId: '818592913245',
    projectId: 'cs-brainova',
    authDomain: 'cs-brainova.firebaseapp.com',
    storageBucket: 'cs-brainova.firebasestorage.app',
    measurementId: 'G-KK4Z8PEM0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-T4I43cPAiJrtGYvym6JknwduSUhwXEc',
    appId: '1:818592913245:android:117d917a9f8b370dacfab4',
    messagingSenderId: '818592913245',
    projectId: 'cs-brainova',
    storageBucket: 'cs-brainova.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmhOA4fUzjMcbxF7LBRxtbdMmc8ROB5ME',
    appId: '1:818592913245:ios:6e68050fbc6d6a72acfab4',
    messagingSenderId: '818592913245',
    projectId: 'cs-brainova',
    storageBucket: 'cs-brainova.firebasestorage.app',
    iosClientId:
        '818592913245-krh6bqlkkf033rtu6nkvkatoda43dts0.apps.googleusercontent.com',
    iosBundleId: 'com.brainova.brainova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmhOA4fUzjMcbxF7LBRxtbdMmc8ROB5ME',
    appId: '1:818592913245:ios:6e68050fbc6d6a72acfab4',
    messagingSenderId: '818592913245',
    projectId: 'cs-brainova',
    storageBucket: 'cs-brainova.firebasestorage.app',
    iosClientId:
        '818592913245-krh6bqlkkf033rtu6nkvkatoda43dts0.apps.googleusercontent.com',
    iosBundleId: 'com.brainova.brainova',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRy7V1svpKFLeV4j2EGxe64BT4lAVbRl8',
    appId: '1:818592913245:web:c2a998149a9a4d06acfab4',
    messagingSenderId: '818592913245',
    projectId: 'cs-brainova',
    authDomain: 'cs-brainova.firebaseapp.com',
    storageBucket: 'cs-brainova.firebasestorage.app',
    measurementId: 'G-KK4Z8PEM0M',
  );
}
